const URL = 'http://localhost:3000/shipments'
const PROD_URL = 'https://my-json-server.typicode.com/ArunRamachandran/ProductHub-React-Redux-BoilerPlate/db'

const DISPATCH_SHIPMENT_DETAILS = 'DISPATCH_SHIPMENT_DETAILS'
const NAVIGATE_TO_DETAILS = 'NAVIGATE_TO_DETAILS'
const UPDATE_SHIPMENT_NAME = 'UPDATE_SHIPMENT_NAME'
const API_REQUEST_INVOKE = 'API_REQUEST_INVOKE'
const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS'
const SEARCH_SHIPMENT_ID = 'SEARCH_SHIPMENT_ID'
const SORT_SHIPMENT_LIST = 'SORT_SHIPMENT_LIST'
const SORT_ASCENDING = 'SORT_ASCENDING'
const SORT_DESCENDING = 'SORT_DESCENDING'
const SORT_BY_ID = 'id'
const SORT_BY_NAME = 'name'
const RESET_TO_DEFAULT = 'RESET_TO_DEFAULT'

export {
    URL,
    PROD_URL,
    DISPATCH_SHIPMENT_DETAILS,
    API_REQUEST_INVOKE,
    API_REQUEST_SUCCESS,
    NAVIGATE_TO_DETAILS,
    UPDATE_SHIPMENT_NAME,
    SEARCH_SHIPMENT_ID,
    SORT_SHIPMENT_LIST,
    SORT_ASCENDING,
    SORT_DESCENDING,
    SORT_BY_ID,
    SORT_BY_NAME,
    RESET_TO_DEFAULT
}
